### ISSUE TITLE
Android versionCode

### ISSUE THREAD

**Issue by benoitdion** [webbertakken/unity-builder#100]
The current versioning strategies successfully set the android `versionName` but do not seem to impact the android `versionCode` which is the more important number when publishing apks. 

I've looked through https://docs.unity3d.com/Manual/CommandLineArguments.html but did not see any way to specify it. Although the `-version` argument also isn't documented so maybe there's a way. Do you know how to specify the android `versionCode` from the cli?

**Comment by webbertakken** [comment]
Hi @benoitdion,

Correct, we're relying on contributions from open source contributors to make this action a smooth ride for everyone. 

Note that there is a lot of logic happening both before starting the unity container and inside it during the build. Versioning has been introduced in one of the recent releases of unity-builder.

The version is generated based on semantic versioning (even if you don't use tags). Custom arguments are parsed by the build script within the build script. Right now the only thing we do with the version is set it as the application version during the build. See [here](https://github.com/webbertakken/unity-builder/blob/master/action/default-build-script/Assets/Editor/Builder.cs) and [here](https://github.com/webbertakken/unity-builder/blob/master/action/default-build-script/Assets/Editor/Versioning/VersionApplicator.cs). 

As I have personally never created and published an android app using unity, it is therefor up to the community to add the necessary functionality that's needed for each platform.

**Comment by benoitdion** [comment]
I looked through the code and it seems straightforward to add on the action side. The key missing piece is how to specify the information so the unity CLI can use it. I can't seem to find anything about it in their doc but `-version` isn't documented either. 

Have you been able to find information about undocumented unity cli arguments?

**Comment by webbertakken** [comment]
Yes, they are in fact not really undocumented CLI arguments, but custom arguments that are parsed using the build script provided by this action. See line 17 of the first reference. That is where the arguments are parsed into a Dictionary. 

This is custom functionality of this actions build script that has no longer anything to do with Unity itself. The build script can be extended and so can the javascript bootstrapper.

**Comment by benoitdion** [comment]
fixed by #101

**Comment by benoitdion** [comment]
@webbertakken do you mind creating a release with the fix?

**Comment by webbertakken** [comment]
@benoitdion not at all. I was waiting for confirmation on tags working too, which they do! 

Your changes have been released in [v1.1](https://github.com/webbertakken/unity-builder/releases/tag/v1.1). 

Let me know if you need any more support.

**Comment by benoitdion** [comment]
thank you!
