### ISSUE TITLE
The build doesn't build the scene

### ISSUE THREAD

**Issue by marce1994** [webbertakken/unity-builder#107]
It builds ok in windows manually, but when i try to build with this action:

![image](https://user-images.githubusercontent.com/358126/85091281-8108e300-b1bd-11ea-9972-a6a85710fca4.png)

How can i know what's happening?

I think its not building the scenes, because the build its 20mb and the one that i build in windows its > 60mb

![image](https://user-images.githubusercontent.com/358126/85091565-0ab8b080-b1be-11ea-83d3-989031a5d80d.png)

```
/github/workspace/./ogirdor/game
-buildTarget
StandaloneWindows64
-customBuildTarget
StandaloneWindows64
-customBuildPath
/github/workspace/build/StandaloneWindows64/StandaloneWindows64.exe
-executeMethod
UnityBuilderAction.Builder.BuildProject
-versioning
```

**Comment by webbertakken** [comment]
Since you're using a custom buildMethod I have no way of knowing what goes wrong in your build

Try using the built-in buildMethod (by not specifying this configuration option) and see if that works. 

It should work, but in case it doesn't, there might be another problem in which case I'd ask you to please be specific about what your logs tell you and what your configuration looks like.

**Comment by Jodebu** [comment]
I do have this exact problem but I am using the default build method. Everithing works perfectly in local but not luck with the action.

You can check the source code and workflow logs [here](https://github.com/Jodebu/clicknrun).

Please do not hesitate to cantact me for any further info you may need.
Thanks in advance.

**Comment by Jodebu** [comment]
I tried to figure out what could be happening when I found out something.

This is my local build:
![image](https://user-images.githubusercontent.com/7392472/85166605-d1d51600-b267-11ea-8dda-05f9a21c7e1b.png)

And this is the CI one:
![image](https://user-images.githubusercontent.com/7392472/85166672-ea453080-b267-11ea-9084-56d3f00f38e1.png)

Could it be that the assets are not being correctly bundled? If so, is it a configuration issue on my side or is something weird going on with action?

Once more, thanks in advance.

**Comment by webbertakken** [comment]
Hi @Jodebu and thanks a lot for giving more input on this.

It's hard to tell for me what is different.  Are you using the exact same version locally as you do in CI? Are there any other things you can identify that are different between your local build and your CI build?

**Comment by Jodebu** [comment]
Versions are identical, but sadly I have made no new discoveries. I encourage you to build them yourself to see if it has to do with my configuration or is OS dependant (my local machine is windows based but the CI VM is linux based).

When I find some time I will post here both builds to see if that helps you narrow down the issue.

**Comment by Jodebu** [comment]
Builds as promised:
[local-build.zip](https://github.com/webbertakken/unity-builder/files/4807065/local-build.zip)
[ci-build.zip](https://github.com/webbertakken/unity-builder/files/4807079/ci-build.zip)

**Comment by webbertakken** [comment]
So I'm fine to give you my input but I'm not going to debug every person's project. I do this in my free time too.

**Comment by Jodebu** [comment]
That is prefectly understandable. Sorry if my wording implied that, but nothing further from my intentions.

If I ever find a workaround or have more specific input I'll let you know. Thanks for saving us a lot time with your GitHub Actions!

**Comment by marce1994** [comment]
This is my configuration, im not using a custom build method, im using the default. The command i posted its autogenerated, i think.

<script src="https://gist.github.com/marce1994/e47e08e4cb72f312380dac586d6b1e53.js"></script>

I'll do what you say about creating a new project and add one by one everything and see what it does.

Thanks for your time.

**Comment by webbertakken** [comment]
> This is my configuration, im not using a custom build method, im using the default. The command i posted its autogenerated, i think.

Ah yea, you're right about that being the default build method.

**Comment by marce1994** [comment]
Ok, thanks ill take a look.

**Comment by marce1994** [comment]
PD: Im using the v0.15 because the v1.0 gives me this error:

![image](https://user-images.githubusercontent.com/358126/85302312-5ea5ec80-b47f-11ea-889b-f1a3aad784a2.png)

But first things first xD

**Comment by webbertakken** [comment]
> PD: Im using the v0.15 because the v1.0 gives me this error:
> 
> ![image](https://user-images.githubusercontent.com/358126/85302312-5ea5ec80-b47f-11ea-889b-f1a3aad784a2.png)
> 
> But first things first xD

This should be fixed on master.

**Comment by marce1994** [comment]
This seems caused by the fact that we aren't actually setting ok the "project folder".
There is a project but its the default one that you "merge" with the build script. I'm trying to change some things to make it work.

**Comment by marce1994** [comment]
How can i know if im setting ok the project path? i suspect that im doing it wrong.

**Comment by webbertakken** [comment]
the root of your repository is the root of your github workspace during the action (if you don't customize the checkout process).

So all you have to do if you Unity project is in the folder `myGame` is use that as the project path. same for subpaths: `my/nested/folder/game`.

If you're just starting off it's probably a good idea to have your project in the root of your repository and that you leave the settings to their defaults.

**Comment by marce1994** [comment]
ok i made it, it works with a new empty project. So i find out that i was setting wrong the projectPath, i was using {reporootname}/{subfolder} and it works with just setting the {subfolder}.

So let it as  ```projectPath: game```  and it worked. @Jodebu try with it xD.

Now i'm getting another problem more related to the project. maybe you may have an idea why.

[4_Unity - Builder.txt](https://github.com/webbertakken/unity-builder/files/4828543/4_Unity.-.Builder.txt)

the only thing i can rescue inside the logs:
```'' is an incorrect path for a scene file. BuildPlayer expects paths relative to the project folder.```

**Comment by webbertakken** [comment]
Could you please open a separate ticket for this?

This is a separate issue and it's useful to separate issues to 1 topic per ticket. That way the history will be better searchable.

**Comment by Jodebu** [comment]
> So let it as `projectPath: game` and it worked. @Jodebu try with it xD.

That's great news! I will try it as soon as I get a chance and report back.
