### ISSUE TITLE
'' is an incorrect path for a scene file. BuildPlayer expects paths relative to the project folder.

### ISSUE THREAD

**Issue by marce1994** [webbertakken/unity-builder#113]
I'm getting a problem related to the project. maybe you may have an idea why.

[4_Unity.-.Builder.txt](https://github.com/webbertakken/unity-builder/files/4833734/4_Unity.-.Builder.txt)

the only thing i can rescue inside the logs:
'' is an incorrect path for a scene file. BuildPlayer expects paths relative to the project folder.

I found this thread https://github.com/google/play-instant-unity-plugin/issues/26 but i dont know if its related.
With an empty new project works, i didnt try to do it in a subfolder like im doing(ill try today at night )

**Comment by JMLegere** [comment]
Do you have any spaces in your directory names for your project folder structure?

**Comment by webbertakken** [comment]
@marce1994 could you share your configuration? Looks like this may be a case of misconfiguration.

**Comment by marce1994** [comment]
what i see weird its this:
```
###########################
#    Project directory    #
###########################

total 9.8M
drwxr-xr-x  6 1001  116 4.0K Jun 29 10:15 .
drwxr-xr-x  6 1001  116 4.0K Jun 29 10:15 ..
-rw-r--r--  1 1001  116 1020 Jun 29 10:12 .gitignore
drwxr-xr-x  3 root root 4.0K Jun 29 10:15 Assets
drwxr-xr-x  2 1001  116 4.0K Jun 29 10:12 Packages
drwxr-xr-x  2 1001  116 4.0K Jun 29 10:12 ProjectSettings
-rw-r--r--  1 1001  116 2.2M Jun 29 10:12 WwiseUnityIntegration_Mac_Src.zip
-rw-r--r--  1 1001  116 5.7M Jun 29 10:12 WwiseUnityIntegration_Windows_Src.zip
drwxr-xr-x 16 1001  116 4.0K Jun 29 10:12 assets
-rw-r--r--  1 1001  116 1.9M Jun 29 10:12 logRunSetup.txt
```
I dont have any folder called "Assets" its called assets.

![image](https://user-images.githubusercontent.com/358126/86019622-34af7580-b9fd-11ea-8598-c6c0464f89cf.png)



Here there are the ProjectSettings:
[ProjectSettings.zip](https://github.com/webbertakken/unity-builder/files/4846150/ProjectSettings.zip)

And my pipeline configuration
[ci.zip](https://github.com/webbertakken/unity-builder/files/4846162/ci.zip)

**Comment by marce1994** [comment]
Oh, that should be the problem ill try again..
```
  m_Scenes:
  - enabled: 1
    path: Assets/Scenes/Menu.unity
    guid: 31dd44640d6c0984d962a07757d0a591
```

I think changing Assets to assets should work(maibe).

**Comment by marce1994** [comment]
![image](https://user-images.githubusercontent.com/358126/86035952-82cf7380-ba13-11ea-9f6f-c86a74d2142c.png)

**Comment by webbertakken** [comment]
Thanks for the updates! It's definitely good to update the status when there's relevant information to share.

Please also mind that every comment in every project that I maintain will kindly send me an email :)

**Comment by marce1994** [comment]
Ok, the problem was that, someone in my team renamed the Assets folder to assets(i don't know why). it works ok in windows, but explodes in linux.

Another bug my project has, its that we are using a plugin that imports Substance shaders, and it crashes every time because it loads first the shader and then the pluign.

Its ok now, it is working. @webbertakken many many thanks for the help, and good luck into your projects.

Regards
