### ISSUE TITLE
Show diff for dirty repository? 

### ISSUE THREAD

**Issue by dogboydog** [webbertakken/unity-builder#117]
Hi, I have been trying out the actions and got a workflow functional with allowDirtyBuild: true. Really cool stuff, thank you for making these actions. I had to add /[Aa]rtifacts/ to .gitignore and fix an issue that was my fault based on inconsistent filename case to reduce the amount of dirty changes in the repo. But it's still showing `ProjectSettings/ProjectSettings.asset` as changed. 

```
 M ProjectSettings/ProjectSettings.asset

##[error]Branch is dirty. Refusing to base semantic version on uncommitted changes
```

I'm happy to get any help for determining why ProjectSettings is changing, but maybe in general it would be nice to have an option like `showDiffOnDirty: true` to show what changes have happened since checkout.

I know there could potentially be many files changed in a dirty repository scenario, but just knowing the filenames isn't quite enough information for me to diagnose the issue.

Related: #95 

Edit: This can be achieved with nice output by issuing `git status --verbose --verbose` or `git --no-pager diff` (conditionally if this option is enabled)

**Comment by dogboydog** [comment]
Would you accept a pull request for this? It seems simple enough to implement

**Comment by webbertakken** [comment]
Yes feel free to open a PR for anything you're missing. As long as it works for everyone :) See also [contributing](https://github.com/webbertakken/unity-builder/blob/master/CONTRIBUTING.md) guide to get you set up quickly.
