### ISSUE TITLE
[failed with exit code 134] Not able to build project

### ISSUE THREAD

**Issue by sudo-make** [webbertakken/unity-builder#128]
Hello guys,
I decided to give CI a go for the first time, and I've stumbled upon an issue that's stopping me from building.
```
Aborting batchmode due to failure:
Scripts have compiler errors.

/home/builduser/buildslave/unity/build/PlatformDependent/Linux/External/baselib/builds/Include/C/Baselib_ThreadLocalStorage.inl.h(12): Assertion failed (rc == 0)
Caught fatal signal - signo:5 code:128 errno:0 addr:(nil)
/home/builduser/buildslave/unity/build/PlatformDependent/Linux/External/baselib/builds/Include/C/Baselib_ThreadLocalStorage.inl.h(12): Assertion failed (rc == 0)
Caught fatal signal - signo:5 code:128 errno:0 addr:(nil)
Obtained 5 stack frames.
#0  0x00562bb4b30c46 in AudioManager::EngineThreadStarted(char const*)
#1  0x00562bb4b309a5 in AudioManager::systemCallback(FMOD_SYSTEM*, FMOD_SYSTEM_CALLBACKTYPE, void*, void*)
#2  0x00562bb89224b4 in FMOD::Thread::callback(void*)
#3  0x007f625f5bc6db in start_thread
#4  0x007f625f2e588f in clone
Aborted (core dumped)
Build failed, with exit code 134
```

I've quite a big project, and I've seen this issue posted on here before but, that would require me having to start my project again (which would be a real pain).

**Comment by webbertakken** [comment]
Hi @sudo-make and thank you for reporting your issue with Unity Builder.

What would require you having to start your project again exactly?

The issue looks specific to your project, but perhaps we need to add some kind of compatibility for something.

**Comment by sudo-make** [comment]
> Hi @sudo-make and thank you for reporting your issue with Unity Builder.
> 
> What would require you having to start your project again exactly?
> 
> The issue looks specific to your project, but perhaps we need to add some kind of compatibility for something.

It's okay, really sorry for troubling you. I didn't realise that may I should have built my project BEFORE trying CI. It turns out it is an issue with my project and nothing to do with unity builder. The exact issue being with the unityeditor namespace being used.

Again, sorry for being 'that guy'.
