### ISSUE TITLE
Is committing the Library folder required for this action to work? 

### ISSUE THREAD

**Issue by nickmarotta** [webbertakken/unity-builder#132]
Hi friends, sorry for the potentially naive question. 

I think I was able to glean this from what your docs suggest, but I wanted to confirm, this action is not able to build without me first committing my `projectRoot/Library` folder correct? 

The reason I ask is that my team had been using the .gitignore file found here: https://github.com/github/gitignore/blob/master/Unity.gitignore which explicitly ignores the `Library` folder. 

We're new to unity so there perhaps there is a best practice we're missing, but it seems like we would have to choose between committing the heavy Library folder so we can have a build pipeline, or keeping the repo light and building ourselves. 

Thanks in advance!

**Comment by webbertakken** [comment]
Hi @nickmarotta,

The `Library` folder should be automatically generated based on your project dependencies. The dependencies file should be part of git, but the library folder should be ignored. 

> We're new to unity so there perhaps there is a best practice we're missing, but it seems like we would have to choose between committing the heavy Library folder so we can have a build pipeline, or keeping the repo light and building ourselves.

So best practice would be to use exactly the `.gitignore` file that you used, which keeps your repository as light as possible. In the pipeline you would just make sure you cache the library folder so that you don't have to download all packages for every run. Caching the `Library` folder is explained in the readme [here](https://unity-ci.com/docs/github/builder) under `Caching`.

> I think I was able to glean this from what your docs suggest

Do you have any tips on how we can improve the documentation?

**Comment by nickmarotta** [comment]
Hi @webbertakken 

Thank you so much for the thoughtful response, that definitely cleared up a lot.

I believe I now understand that the `Library` folder should be created by the build action, and that the first time I run this action successfully, the cache won't exist. Once the build is successful the cache action will kick off a "post action" and save the `Library` folder for faster builds. 

I think my actual issue
 is that I don't understand the pathing structure that the action uses. (Perhaps this is due to a lack of familiarity with git actions, I will continue to research this.) There is no nesting for my unity project, the root of the git repo is the root of the unity project, therefore I've not used the `projectPath` config variable. 

I've attached my build action output log, and main.yml, if I'm able to resolve this I'd be happy to assess if there was something that didn't click for me in the documentation! 

Thanks again ~ 

[unity-builder.log](https://github.com/webbertakken/unity-builder/files/5038716/unity-builder.log)
[main.yml.txt](https://github.com/webbertakken/unity-builder/files/5038721/main.yml.txt)

**Comment by webbertakken** [comment]
Correct.

You may simply use 

```yaml
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-
```

as per the [docs](https://unity-ci.com/docs/github/builder#caching).

**Comment by nickmarotta** [comment]
Based on the attached log above do you have any insight as to why the build is failing? I'm not using much configuration at all for the build action (also attached), and don't understand why the build fails.

**Comment by webbertakken** [comment]
Sure, my answer was based on that log. 

You shouldn't reference your project because you're already in that folder.

**Comment by nickmarotta** [comment]
My cache action now mirrors exactly what you've suggested, but the build action still generates the following: 
```
###########################
#    Building platform    #
###########################

2020.1.0f1
Build succeeded
Making the following path executable: /github/workspace/build/StandaloneOSX/StandaloneOSX.app/Contents/MacOS/*
chmod: cannot access '/github/workspace/build/StandaloneOSX/StandaloneOSX.app/Contents/MacOS/*': No such file or directory
```

**Comment by webbertakken** [comment]
This is probably just `2020.1.0f1` not working properly. I've seen more issues in the 2020 range. 

I think it would be wise to try some other versions of unity. This might very well be a bug in unity or in the docker image.

**Comment by webbertakken** [comment]
Confirmed about the 2020.1 issue: https://github.com/webbertakken/unity-builder/issues/135

**Comment by nickmarotta** [comment]
Hey sorry to comment on something that is closed, but I wanted to update that I did try version 2019.4.8f1 and still received an empty build. I checked out some other issues that were raised and it seems like I'm not the only one experiencing this, per https://github.com/webbertakken/unity-builder/issues/136. I'll try some of the steps listed in that issue. 

Also great to hear about issue #135! Thank you for your time and hard work!

**Comment by webbertakken** [comment]
@nickmarotta thanks for your feedback.

As it's no longer about the question whether or not you should be committing the Library folder, I recommend you add your comments in the two issues that you mentioned, so that others also get confirmation about their findings, perhaps together we can find a solution for them.
