### ISSUE TITLE
Help. "Requesting activation (personal license). Unclassified error occured while trying to activate license."

### ISSUE THREAD

**Issue by bautrey37** [webbertakken/unity-builder#159]
Hello Webbertakken! 

I love you are building Unity CI plugins.  I am working on trying to get my build process to work on my game but I've come across this problem.  I hope this is the right place to ask for help. There is nothing in the game repo yet btw... 

On the build log I'm getting this. Which seems like it can not activate the license properly. 

```
Successfully tagged unity-builder:2020.1.3f1-mac
/usr/bin/docker run --workdir /github/workspace --rm --env UNITY_LICENSE --env UNITY_LICENSE_FILE --env UNITY_EMAIL --env UNITY_PASSWORD --env UNITY_SERIAL --env UNITY_VERSION=2020.1.3f1 --env PROJECT_PATH=. --env BUILD_TARGET=StandaloneOSX --env BUILD_NAME=StandaloneOSX --env BUILD_PATH=build/StandaloneOSX --env BUILD_FILE=StandaloneOSX --env BUILD_METHOD= --env VERSION=0.0.16 --env ANDROID_VERSION_CODE=16 --env ANDROID_KEYSTORE_NAME= --env ANDROID_KEYSTORE_BASE64= --env ANDROID_KEYSTORE_PASS= --env ANDROID_KEYALIAS_NAME= --env ANDROID_KEYALIAS_PASS= --env CUSTOM_PARAMETERS= --env HOME=/github/home --env GITHUB_REF --env GITHUB_SHA --env GITHUB_REPOSITORY --env GITHUB_ACTOR --env GITHUB_WORKFLOW --env GITHUB_HEAD_REF --env GITHUB_BASE_REF --env GITHUB_EVENT_NAME --env GITHUB_WORKSPACE=/github/workspace --env GITHUB_ACTION --env GITHUB_EVENT_PATH --env RUNNER_OS --env RUNNER_TOOL_CACHE --env RUNNER_TEMP --env RUNNER_WORKSPACE --volume /var/run/docker.sock:/var/run/docker.sock --volume /home/runner/work/_temp/_github_home:/github/home --volume /home/runner/work/_temp/_github_workflow:/github/workflow --volume /home/runner/work/Outlight/Outlight:/github/workspace unity-builder:2020.1.3f1-mac
Requesting activation (personal license)
Unclassified error occured while trying to activate license.
Exit code was: 1
Error: The process '/usr/bin/docker' failed with exit code 1
```

My Github Action script is here: https://github.com/bautrey37/Outlight/blob/main/.github/workflows/main.yml

For the UNITY_LICENSE, I am using my serial key on my organization in Unity. I have a Unity Pro license from being a student.  I hope that this CI workflow is applicable to this license type. I'm not completely sure if this is the right license to use for the secret.

**Comment by webbertakken** [comment]
Hi @bautrey37 and thank you for reporting your issue with Unity Builder.

> For the UNITY_LICENSE, I am using my serial key on my organization in Unity.

Is there a special reason you're doing this? Because the readme never tells you to do that, and out of the box this is not expected to work.

**Comment by bautrey37** [comment]
Thanks for responding! It seems though I only read the `Getting started` part and not the next section of `Activation`.  I don't know why, I guess I assumed that Getting started was all that I needed and I wasn't knowledgable about Unity licenses in how to activate them.  I thought you just go online and find it like in other licenss.   

When I activate my license, I get two options to choose from `plus or pro` and `personal`. I got them both, but on my profile, it says I have Unity Pro subscription.  Honestly, I have no idea what the difference but the personal seems to be the classic free license. The instructions don't mention this part.  I think it might not matter for this Unity CI, but I feel like the instructions should mention this part. 

On the step of `copy the contents your license file into it.` of section `Converting into a license`, I feel like it should say, 
`copy the entire XML contents of your license file into it.`
Because when it said content, I thought it means to go inside and find the license key, such as the <SignatureValue> contents. But that is not the case.  

Now on my build, it is able to find my license correctly.  But now it says, `Segmentation fault (core dumped)`.  I remember seeing something like in some other issues on Github. Do you know what to do next?
https://github.com/bautrey37/Outlight/runs/1205833929?check_suite_focus=true

**Comment by GabLeRoux** [comment]
> I feel like it should say,
> `copy the entire XML contents of your license file into it.`

Documentation can definitely be improved, feel free to open a pull request 👍 

> Now on my build, it is able to find my license correctly. But now it says, Segmentation fault (core dumped). I remember seeing something like in some other issues on Github. Do you know what to do next?

You may also search here:
https://gitlab.com/gableroux/unity3d-gitlab-ci-example/-/issues?scope=all&utf8=%E2%9C%93&state=all&search=Segmentation+fault+(core+dumped).

I'll close this issue because initial activation issue is now solved by reading the documentation. Feel free to open a new issue with more details specific to your `Segmentation fault (core dumped)` error. (Ex; full build log, unity version, a link to your project if it's open source, the things you've tried so far, etc).

Good luck! 🎉

**Comment by bautrey37** [comment]
Ok no problem. Thanks for the help. I'm working on a PR for the doc update.

**Comment by bautrey37** [comment]
https://github.com/Unity-CI/Website/pull/41

**Comment by webbertakken** [comment]
See also https://github.com/webbertakken/unity-builder/issues/135 to solve your problem.
