### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by iserofeev** [webbertakken/unity-builder#169]
Hi, I encountered this error when trying to build my project to android. 
After import all assets build crash with error which I attached below 
Is that a my mistake, or may be someone have any ideas or workarounds?

```
Scripts have compiler errors. 
19793
(Filename: ./Runtime/Utilities/Argv.cpp Line: 376)
19794

19795

19796
Aborting batchmode due to failure:
19797
Scripts have compiler errors.
19798

19799
[Performance] Application.InitializeProject                                 :        1 samples, Peak.  1.36 ks (1.0x), Avg.  1.36 ks, Total. 1.360 ks (99.9%)
19800
[Performance] Application.PackageManager.StartServer                        :        1 samples, Peak.  3.89 ms (1.0x), Avg.  3.89 ms, Total. 3.895 ms (0.0%)
19801
[Performance] Application.IsBrowserCacheEmpty                               :        1 samples, Peak.   710 us (1.0x), Avg.   710 us, Total. 709.6 us (0.0%)
19802
[Performance] Application.AcquireProjectLock                                :        1 samples, Peak.  2.37 ms (1.0x), Avg.  2.37 ms, Total. 2.371 ms (0.0%)
19803
[Performance] Application.InitializeEngineNoGraphics                        :        1 samples, Peak.   394 ms (1.0x), Avg.   394 ms, Total. 393.5 ms (0.0%)
19804
[Performance] Application.PackageManager.Initialize                         :        1 samples, Peak.   884 ms (1.0x), Avg.   884 ms, Total. 883.8 ms (0.1%)
19805
[Performance] CurlRequestCheck                                              :       18 samples, Peak.   213 us (5.4x), Avg.  39.7 us, Total. 713.8 us (0.0%)
19806
[Performance] PackageManager::RunRequestSynchronously                       :      621 samples, Peak.   565 us (27.8x), Avg.  20.3 us, Total. 12.61 ms (0.0%)
19807
[Performance] Application.EngineGraphics.Initialize                         :        1 samples, Peak.  2.33 s (1.0x), Avg.  2.33 s, Total. 2.332 s (0.2%)
19808
[Performance] Application.GI.Initialize                                     :        1 samples, Peak.   860 ms (1.0x), Avg.   860 ms, Total. 859.7 ms (0.1%)
19809
[Performance] Application.LoadAllDefaultResourcesFromEditor                 :        1 samples, Peak.  5.20 ms (1.0x), Avg.  5.20 ms, Total. 5.201 ms (0.0%)
19810
[Performance] Application.LoadMonoAssemblies                                :        1 samples, Peak.  3.67 s (1.0x), Avg.  3.67 s, Total. 3.674 s (0.3%)
19811
[Performance] ProcessService.EditorAfterLoadAllAssemblies                   :        3 samples, Peak.  57.9 ms (1.4x), Avg.  41.9 ms, Total. 125.8 ms (0.0%)
19812
[Performance] Application.ReadLicenseInfo                                   :        1 samples, Peak.  10.1 ms (1.0x), Avg.  10.1 ms, Total. 10.06 ms (0.0%)
19813
[Performance] Application.InitialScriptRefresh                              :        1 samples, Peak.   318 s (1.0x), Avg.   318 s, Total. 318.4 s (23.4%)
19814
[Performance] BuildCatalog                                                  :        2 samples, Peak.   324 ms (1.2x), Avg.   272 ms, Total. 544.5 ms (0.0%)
19815
[Performance] Application.AssetDatabase.Refresh                             :        1 samples, Peak.   997 s (1.0x), Avg.   997 s, Total. 996.6 s (73.2%)
19816
[Performance] SceneDataContainer.TransformHierarchyChangedSetParentCallback :    34131 samples, Peak.  89.3 us (101.8x), Avg.   877 ns, Total. 29.95 ms (0.0%)
19817
[Performance] SceneVisibilityState.IsFlagSetInParents                       :   106275 samples, Peak.  88.5 us (178.3x), Avg.   496 ns, Total. 52.76 ms (0.0%)
19818
[Performance] Application.ImportAssetsWithMismatchingAssetImporterVersion   :        1 samples, Peak.   552 ms (1.0x), Avg.   552 ms, Total. 552.1 ms (0.0%)
19819
[Performance] Application.SyncCurrentColorSpace                             :        1 samples, Peak.   179 ms (1.0x), Avg.   179 ms, Total. 178.9 ms (0.0%)
19820
[Performance] Application.OnUsbDevicesChanged                               :        1 samples, Peak.  10.2 us (1.0x), Avg.  10.2 us, Total. 10.20 us (0.0%)
19821
[Performance] Application.AssetDatabase.SaveAssets                          :        1 samples, Peak.   498 ms (1.0x), Avg.   498 ms, Total. 498.0 ms (0.0%)
19822
[Performance] Application.AssetInstanceCacheUpdate                          :        1 samples, Peak.   300 ns (1.0x), Avg.   300 ns, Total. 300.0 ns (0.0%)
19823
[Performance] Application.UnityExtensions.Initialize                        :        1 samples, Peak.  2.90 ms (1.0x), Avg.  2.90 ms, Total. 2.903 ms (0.0%)
19824
[Performance] Application.InitializeManagedCompilationPipeline              :        1 samples, Peak.   195 ms (1.0x), Avg.   195 ms, Total. 195.0 ms (0.0%)
19825
[Performance] Application.ExecuteStartups                                   :        1 samples, Peak.   236 ms (1.0x), Avg.   236 ms, Total. 235.7 ms (0.0%)
19826
[Performance] Application.RebuildOSMenu                                     :        1 samples, Peak.  74.4 ms (1.0x), Avg.  74.4 ms, Total. 74.40 ms (0.0%)
19827
[Performance] UpdateAllMenus                                                :        1 samples, Peak.  74.4 ms (1.0x), Avg.  74.4 ms, Total. 74.39 ms (0.0%)
19828
[Performance] Application.editorInitializingProject                         :        1 samples, Peak.  29.3 us (1.0x), Avg.  29.3 us, Total. 29.30 us (0.0%)
19829
[Performance] GUIView.RepaintAll.PlayerLoopController                       :        1 samples, Peak.   900 ns (1.0x), Avg.   900 ns, Total. 900.0 ns (0.0%)
19830
[Performance] Application.InvokeFinishedLoadingProject                      :        1 samples, Peak.  70.5 ms (1.0x), Avg.  70.5 ms, Total. 70.49 ms (0.0%)
19831
[Performance] ProcessService.OnProjectLoaded                                :        1 samples, Peak.  56.9 ms (1.0x), Avg.  56.9 ms, Total. 56.93 ms (0.0%)
19832
Cleanup mono
19833
debugger-agent: Unable to listen on 38
19834
geForIconForExtension
19835
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19836
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19837
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19838
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19839
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19840
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19841
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19842
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19843
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19844
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19845
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19846
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19847
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19848
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19849
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19850
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19851
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19852
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19853
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19854
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19855
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19856
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19857
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19858
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19859
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19860
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19861
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19862
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19863
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19864
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19865
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19866
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19867
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19868
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19869
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19870
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19871
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19872
./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
19873
Compressing using quality level 127
19874
./Editor/Platform/Linux/UsbDevices.cpp:UsbDevicesQuery
19875
Build failed, with exit code 1
19876
```

**Comment by brett-estabrook** [comment]
I know there are some known issues with building on android, but I'm curious if there's a current known working configuration. Below is my current problem.

> JDK was not installed with Unity at /opt/Unity/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK, disabling "Installed with Unity" checkbox to look for alternative locations.

> Uploading Crash Report
CommandInvokationFailure: Unable to update the SDK. Please run the SDK Manager manually to make sure you have the latest set of tools and the required platforms installed. 
/opt/android/sdk/tools/bin/sdkmanager tools platform-tools "build-tools;28.0.3"

> stderr[
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Warning: File /github/home/.android/repositories.cfg could not be loaded.
Warning: Failed to read or create install properties file.
]
> stdout[
Loading package information...                                                  
Loading local repository...                                                     
[                                       ] 3% Loading local repository...        
[                                       ] 3% Fetch remote repository...         
[                                       ] 3% Fetch remote repository...         
[=                                      ] 3% Fetch remote repository...         
[=                                      ] 4% Fetch remote repository...         
[=                                      ] 4% Fetch remote repository...         
[=                                      ] 4% Fetch remote repository...         
[==                                     ] 5% Fetch remote repository...         
[==                                     ] 6% Fetch remote repository...         
[==                                     ] 6% Computing updates...               
[===                                    ] 8% Computing updates...               
[===                                    ] 8% Computing updates...               
[===                                    ] 10% Computing updates...              
[===                                    ] 10% Installing Android SDK Build-Tools
[===                                    ] 10% Installing Android SDK Build-Tools
]
exit code: 1
  at UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) [0x00033] in <d7067458867d436a825598eb5e44cdf0>:0 
  at UnityEditor.Android.Command.RunWithStdin (System.Diagnostics.ProcessStartInfo psi, System.String errorMsg, System.Collections.Generic.IEnumerable`1[T] input) [0x00078] in <d7067458867d436a825598eb5e44cdf0>:0 
  at UnityEditor.Android.AndroidSDKTools.RunAndroidSdkTool (System.String toolName, System.String arguments, System.Boolean updateCommand, System.String errorMsg, System.String toolsDir, System.String[] warningsToIgnore) [0x0005f] in <d7067458867d436a825598eb5e44cdf0>:0 
  at UnityEditor.Android.AndroidSDKTools.RunAndroidSdkTool (System.String toolName, System.String arguments, System.Boolean updateCommand, System.String errorMsg) [0x00001] in <d7067458867d436a825598eb5e44cdf0>:0 
  at UnityEditor.Android.AndroidSDKTools.UpdateSDK () [0x0009f] in <d7067458867d436a825598eb5e44cdf0>:0 
  at UnityEditor.Android.PostProcessor.Tasks.CheckAndroidSDK+SDKComponentDetector.Update (UnityEditor.Android.AndroidSDKTools sdkTools, System.Version minVersion, UnityEditor.Android.PostProcessor.ProgressHandler onProgress) [0x0002a] in <d7067458867d436a825598eb5e44cdf0>:0 
  at UnityEditor.Android.PostProcessor.Tasks.CheckAndroidSDK.EnsureSDKComponentVersion (System.Version minVersion, UnityEditor.Android.PostProcessor.Tasks.CheckAndroidSDK+SDKComponentDetector detector) [0x00072] in <d7067458867d436a825598eb5e44cdf0>:0 
  at UnityEditor.Android.PostProcessor.Tasks.CheckAndroidSDK.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) [0x00128] in <d7067458867d436a825598eb5e44cdf0>:0 
  at UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) [0x00078] in <d7067458867d436a825598eb5e44cdf0>:0 
UnityEditor.BuildPipeline:BuildPlayerInternalNoCheck(String[], String, String, BuildTargetGroup, BuildTarget, BuildOptions, Boolean)
UnityEditor.BuildPipeline:BuildPlayerInternal(String[], String, String, BuildTargetGroup, BuildTarget, BuildOptions) (at /home/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:376)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, String, BuildTargetGroup, BuildTarget, BuildOptions) (at /home/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:275)
UnityEditor.BuildPipeline:BuildPlayer(BuildPlayerOptions) (at /home/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:258)
UnityBuilderAction.Builder:BuildProject() (at Assets/Editor/Editor/Builder.cs:38)
 
> (Filename: <d7067458867d436a825598eb5e44cdf0> Line: 0)

**Comment by iserofeev** [comment]
Hey, yes, build to android is possible, and I’m successfully did it.

In my case it was unobvious mistake, the default build scripts add “Environment” namespace to parse arguments, and at the same time Environment namespace already exists in my project, and it’s mean game environment 😄. So, when I tried to build on my machine everything was well, but crashing on CI. 
May be need to call parse method with “System.Environment” to avoid in future.


Now to your problem. After I solve problem that described above, I ran into problem like your. As far, as i understand, errors with JDK, SDK and NDK are related to docker images. So, in new [v2.0-alpha-1](https://github.com/webbertakken/unity-builder/releases/tag/v2.0-alpha-1) docker images using android tools installed with unity hub. 
**But**, it will crash because when unity start argument "-butchmode" repeated twice.

I'm sure it will be fixed in future, because it's alpha, so if you want to use it right now, I made little fix to Android builds and until the problem is solved, you can use this:

` - name: Build project
        id: build
        uses: iserofeev/unity-builder@aa43a36ab902e8264c44f803bd94b0c921825734
        with:
          unityVersion: 2019.4.13f1
          targetPlatform: Android`

Hope, it will help you

**Comment by webbertakken** [comment]
This should be solved in the latest alpha version for v2

**Comment by bartutiryakioglu** [comment]
Is this bug resolved because I am having the same issue

**Comment by vitalyk-multinarity** [comment]
The same issue (as far as I see).

**Comment by AhmadMansy** [comment]
same issue here
