### ISSUE TITLE
Android build fails with an ArgumentException: An item with the same key has already been added. Key: batchmode

### ISSUE THREAD

**Issue by Philipp-M** [webbertakken/unity-builder#172]
**Bug description**

While building for Android, I've encountered an `ArgumentException: An item with the same key has already been added. Key: batchmode`.
This seems to happen in the injected builder script.
I've not added any additional parameters to the builder.  

**How to reproduce**

Here is a minimal reproduction action that was used:

```yml
jobs:
  buildAndTestForSomePlatforms:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      - uses: webbertakken/unity-builder@v2.0-alpha-1
        with:
          allowDirtyBuild: true
          projectPath: 'Project'
          unityVersion: '2019.4.12f1'
          targetPlatform: 'Android'
```

**Expected behavior**

As seen in the log, a duplicate key `batchmode` was somehow added to the cli as argument, this shouldn't happen in my case.
I think it's interesting why `batchmode` was added two times although it was never specified.

But there may be cases where it does, so multiple arguments of the same name should probably just overwrite the previous given argument value instead of throwing an exception,  

**Additional details**

(relevant) Log:

```
...
Initializing Unity extensions:
 '/opt/unity/Editor/Data/UnityExtensions/Unity/UnityVR/Editor/UnityEditor.VR.dll'  GUID: 4ba2329b63d54f0187bcaa12486b1b0f
UpdateMenuTitleForLanguage: 10
Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
System memory in use before: 38.8 MB.
System memory in use after: 36.5 MB.

Unloading 2341 unused Assets to reduce memory usage. Loaded Objects now: 1944.
Total: 12.591500 ms (FindLiveObjects: 1.199600 ms CreateObjectMapping: 0.264100 ms MarkObjects: 6.429600 ms  DeleteObjects: 4.697200 ms)


###########################
#    Parsing settings     #
###########################


Found flag "batchmode" with value "".
Found flag "batchmode" with value "".
ArgumentException: An item with the same key has already been added. Key: batchmode
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <9577ac7a62ef43179789031239ba8798>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
  at UnityBuilderAction.Input.ArgumentsParser.ParseCommandLineArguments (System.Collections.Generic.Dictionary`2[System.String,System.String]& providedArguments) [0x00135] in /github/workspace/apps/template/unity/Template/Assets/Editor/Editor/Input/ArgumentsParser.cs:76 
  at UnityBuilderAction.Input.ArgumentsParser.GetValidatedOptions () [0x00001] in /github/workspace/apps/template/unity/Template/Assets/Editor/Editor/Input/ArgumentsParser.cs:15 
  at UnityBuilderAction.Builder.BuildProject () [0x00001] in /github/workspace/apps/template/unity/Template/Assets/Editor/Editor/Builder.cs:17 
 
(Filename: <9577ac7a62ef43179789031239ba8798> Line: 0)

executeMethod method UnityBuilderAction.Builder.BuildProject threw exception. 
(Filename: ./Runtime/Utilities/Argv.cpp Line: 376)


Aborting batchmode due to failure:
executeMethod method UnityBuilderAction.Builder.BuildProject threw exception.
...
```

I had to add `allowDirtyBuild`, as I otherwise got this error:

```
diff --git a/libs/unity/SharpZipLib/Runtime/ICSharpCode.SharpZipLib.dll b/libs/unity/SharpZipLib/Runtime/ICSharpCode.SharpZipLib.dll
index c33040b..37265cb 100644
Binary files a/libs/unity/SharpZipLib/Runtime/ICSharpCode.SharpZipLib.dll and b/libs/unity/SharpZipLib/Runtime/ICSharpCode.SharpZipLib.dll differ

 M apps/template/web/public/favicon.ico
 M libs/unity/SharpZipLib/Runtime/ICSharpCode.SharpZipLib.dll

Error: Branch is dirty. Refusing to base semantic version on uncommitted changes
```

I'm not sure if this is connected somehow, because I don't think `allowDirtyBuild` is the right way, but I don't get past that without a dirty build. I've previously experimented a lot, so this might be caused by previously cached files probably (although I'm not using a cache here).
Is there any way how to completely clean up the previous state/repo, to avoid the `allowDirtyBuild` flag?

**Comment by webbertakken** [comment]
Hey again @Philipp-M and thanks for reporting this issue.

> While building for Android, I've encountered an ArgumentException: An item with the same key has already been added. Key: batchmode.

This is indeed a bug. `-batchmode` has to be removed from all scripts, as that flag is already included in the docker image by default.

cc: @BLaZeKiLL looks like we missed this one.

> I had to add allowDirtyBuild, as I otherwise got this error

I think it would be better to either gitignore or add these files to you repository. This looks like it works as designed. You shouldn't make production builds with floating files, unless you're having a pre-build step in a separate action.

In this case you could consider adding the pre-build step to your actual build or to ignore any pre-built files in your `.gitignore`

**Comment by Philipp-M** [comment]
Thanks for the answer,

> I think it would be better to either gitignore or add these files to you repository. This looks like it works as designed. You shouldn't make production builds with floating files, unless you're having a pre-build step in a separate action.
> 
> In this case you could consider adding the pre-build step to your actual build or to ignore any pre-built files in your .gitignore

Interestingly all of these files are tracked and were tracked already as I started my experiments. I'm a little bit clueless, what might cause the dirty branch. My initial guess was that caching might be a problem, so I disabled all caching but still got the error.

**Comment by webbertakken** [comment]
If the files are already tracked, they somehow change. Otherwise your branch wouldn't be dirty. This is using git's native functionality from `git describe`.

Could you perhaps share your full workflow?

**Comment by Philipp-M** [comment]
Thanks for the help, I've found the issue, it had to do with git lfs:
The problematic files were tracked normally, but were listed in .gitattributes as lfs files. So git lfs tried to resolve them somehow and failed (and modified them?).
The solution was to untrack these files, and then track them as lfs files, see also this for additional info:
https://stackoverflow.com/questions/46704572/git-error-encountered-7-files-that-should-have-been-pointers-but-werent.

Now I'm running into the originally mentioned issue, but without `allowDirtyBuild` (so that doesn't cause the issue).
