### ISSUE TITLE
unity-builder@v2.0-aplha-5 create 0 size builds

### ISSUE THREAD

**Issue by kreghek** [webbertakken/unity-builder#183]
**Bug description**

I tried to port my pipeline from `v1.5` to `v2.0-aplha-5`. Now I have empty artefacts.

You can see my changes in https://github.com/kreghek/Zilon_Roguelike/pull/905/files#diff-db640e5698dc2c7d6326459c597f67e80e0d8061bb9e89697b4bf4a1f765568f

Key changes is:

```
- uses: webbertakken/unity-builder@v2.0-aplha-5
```

**How to reproduce**

There is results of Github actions:
https://github.com/kreghek/Zilon_Roguelike/runs/1435830765

![image](https://user-images.githubusercontent.com/2405499/99927717-f1252180-2d78-11eb-80f7-e9ea0d63c91d.png)

**Expected behavior**

I thought it would be enough to just change the version.

**Additional details**

I can explain more about my pipeline. But I dont understend which details are significant. Please, ask in comments.

**Comment by creichel** [comment]
Apart from that, the version tag has a misspelled `alpha` (`aplha`)...

**Comment by kreghek** [comment]
> Apart from that, the version tag has a misspelled `alpha` (`aplha`)...

Yes, I used `aplha`. Because `alpha` fail build at all.

**Comment by kreghek** [comment]
I note next line in release notes:
- This also means that licenses have to be reactivated when upgrading.

I miss this thing early. Now I used `webbertakken/unity-request-manual-activation-file@v1.1` How to port activation to new images? Cant find it in the docs.

**Comment by webbertakken** [comment]
> Apart from that, the version tag has a misspelled `alpha` (`aplha`)...

yea my bad, the release is actually named that.

> I miss this thing early. Now I used webbertakken/unity-request-manual-activation-file@v1.1 How to port activation to new images? Cant find it in the docs.

Also use the alpha version for that action (see [releases](https://github.com/webbertakken/unity-request-activation-file/releases)).

**Comment by kreghek** [comment]
Cool. Activation from `2.0-alpha` fixed zero-size build artefacts. Thanks!
