### ISSUE TITLE
Feature request: Support for custom command-line args

### ISSUE THREAD

**Issue by JesseTG** [webbertakken/unity-builder#19]
I build my project with [Trimmer](https://github.com/sttz/trimmer). Doing so on the command line is a little different; you don't need to specify the platform explicitly (because your Trimmer profile lists it in the file), but you do need to add a `-profileName` argument in order to select a build profile. If the build profile supports multiple platforms but you only want to build for one of them, you need to say so with another argument as well.

**Comment by webbertakken** [comment]
That definitely looks like something that might be useful to be compatible with. I'm not sure if i'll get to this, but (anyone) feel free to submit a PR with your suggested approach.

**Comment by webbertakken** [comment]
@JesseTG do you think above PR could work for you?

**Comment by JesseTG** [comment]
It would, actually, thank you!

**Comment by webbertakken** [comment]
Cool! Very curious to hear your findings. It's been released in [builder v0.9](https://github.com/webbertakken/unity-builder/releases/tag/v0.90)

Feel free to give any feedback you might have.

**Comment by Filiecs** [comment]
I was testing this and an issue I noticed is that _all_ the command line args are passed in as a single string. This means that they are treated as a single argument when parsing `System.Environment.GetCommandLineArgs();`
I would suggest removing the quotes around "$CUSTOM_PARAMETERS" in the build.sh file to allow the user themselves to decide if they want their arguments passed in as a single string or not.

**Comment by webbertakken** [comment]
Works in above PRs as shown here: https://github.com/webbertakken/unity-builder/runs/439419496?check_suite_focus=true#step:4:439

**Comment by webbertakken** [comment]
Released for test-runner in [test-runner v1.4](https://github.com/webbertakken/unity-test-runner/releases/tag/v1.4)
Released for builder in [builder v0.11](https://github.com/webbertakken/unity-builder/releases/tag/v0.11)

**Comment by webbertakken** [comment]
@Filiecs please let me know if that works for you

**Comment by Filiecs** [comment]
Yes this works great!
