### ISSUE TITLE
Doc error: buildMethod

### ISSUE THREAD

**Issue by millonf** [webbertakken/unity-builder#41]
Hello,

I believe the doc has an error for `buildMethod`, the doc examples says as follow : `buildMethod: EditorNamespace.BuilderClassName.StaticBulidMethod` , but you should write `buildMethod: BuilderClassName.StaticBulidMethod` without the `EditorNameSpace`.

It wasn't working with it or with `UnityEditor`, but having the class inside `Assets/Editor/` folder and calling just the class and static method is enough.

Cheers

**Comment by webbertakken** [comment]
According to official [docs](https://docs.unity3d.com/Manual/CommandLineArguments.html) If that class uses a namespace, you will also have to specify it.

I agree in builder docs it's a little ambiguous. It could be changed to be a little bit clearer.
