### ISSUE TITLE
Support put UNITY_LICENSE in file

### ISSUE THREAD

**Issue by litefeel** [webbertakken/unity-builder#67]
Hi.
My unified license is not important.
Can I put it in the file. 
And set the file path to an environment variable
Thanks.

**Comment by webbertakken** [comment]
This is not considered good practice, as it would require you to commit your license file or do things that are actually harder than just copy pasting it into a secret variable.

Could you give some more context as to why you're trying to this?

**Comment by litefeel** [comment]
Thank you for your reply.
I know storing license files is not secure, but my license is not important.
I have many worker projects and a license project. These worker project will access the license from the license project. I don't need to set up a license for each project.
The license will expire after a while, and then I fix it in the license project and other projects will work without change anything

**Comment by webbertakken** [comment]
Support has been added in #69
