### ISSUE TITLE
BuildFailedException: Graphic API OpenGLCore is not supported with High Definition Render Pipeline (HDRP)

### ISSUE THREAD

**Issue by quietdimensions** [webbertakken/unity-builder#79]
Hi, is HDRP supported? I switched my test project to HDRP and I am getting this message: "Build failed, with exit code 101".

Thanks :)

**Comment by webbertakken** [comment]
Hi @quietdimensions, thanks for reporting your issue with unity builder.

I see no reason why it wouldn't work, but I'd love to learn more about which errors are you getting in your logs. Could you dig through the output log and see if you find any errors that are more specific?

**Comment by quietdimensions** [comment]
Hi, I found this error:
`Error building Player: BuildFailedException: The platform StandaloneOSX with the graphic API OpenGLCore is not supported with High Definition Render Pipeline`

If you wanna see whole log you can find it [here](https://www.dropbox.com/s/gmc28zx3ccr0nnr/Build%20my%20project_logs.zip?dl=0)

**Comment by webbertakken** [comment]
Looks like OpenGLCore is indeed not supported by HDRP. 

On the Unity forums someone seems to have found the [solution](https://forum.unity.com/threads/error-while-setting-up-hd-rendering-pipeline-on-mac.540830/#post-5316774) for a similar issue that you're having; they are changing the graphics API in the player settings to `Metal`. 

Let me know if that works for you.

**Comment by quietdimensions** [comment]
Hi, I had to uncheck the Auto Graphics API for Mac and delete OpenGL Core from the list (I don't know why... Metal was first in the list - see on the picture) and now it's working. Thanks for the help!

<img width="707" alt="Screenshot 2020-04-20 at 21 44 48" src="https://user-images.githubusercontent.com/57481585/79794309-52ec5b80-8352-11ea-8655-f52f5edb83a7.png">

**Comment by webbertakken** [comment]
@quietdimensions Glad that worked. Thank you for sharing your solution!
