### ISSUE TITLE
Explain recommended action when branch is dirty

### ISSUE THREAD

**Issue by webbertakken** [webbertakken/unity-builder#95]
The message from builder when the branch is dirty currently outputs this

```console
##[error]Branch is dirty. Refusing to base semantic version on uncommitted changes
```

It would be better if it also includes an explanation of why a branch should usually not be dirty, and offer the possibility of the `allowDirtyBuild` flag, referring to the readme.

**Dirty**

Dirty means that you have made changes after you have ran the checkout job.
If you don't mean to change files, it's better to check what is going on first, and fix that instead of using the `allowDirtyBuild` flag.

**Unity test runner**

In version `unity-test-runner@v1.3` the artifacts folder is not yet deleted. For making it delete the artifacts folder there is https://github.com/webbertakken/unity-test-runner/issues/58 in test-runner

**Comment by darrencperry** [comment]
It looks like the branch can also become dirty when specifying a different unity version to the project in the action. The ProjectSettings/ProjectVersion.txt seems to get modified and you then get the above error.

**Comment by webbertakken** [comment]
Closing this as we're now logging the diff and the issue hasn't been very active, anyone is free to send a PR either way
