### ISSUE TITLE
How to add BuildOptions

### ISSUE THREAD

**Issue by snake302** [webbertakken/unity-builder#98]
Hi there!

I want to add compression build option for iOS Build (https://docs.unity3d.com/ScriptReference/BuildOptions.CompressWithLz4HC.html) is this possible?

**Comment by webbertakken** [comment]
Hi @snake302,

Did you try it?

**Comment by mastef** [comment]
To re-open this, as it's the only hit for `CompressWithLz4HC` in the repo : 

https://game.ci/docs/github/builder/#customparameters
"To pass [Unity Build Options](https://docs.unity3d.com/ScriptReference/BuildOptions.html) (for example, customParameters: -standaloneBuildSubtarget Server will do server builds)"

So in this case this would possibly be : 

```
- uses: game-ci/unity-builder@v3
  with:
    customParameters: -CompressWithLz4HC
```

( Haven't tested yet, looking for the solution as well )

**Comment by gotchipete** [comment]
Curious about this too. Did you figure it out @mastef ?

**Comment by mastef** [comment]
> Curious about this too. Did you figure it out [@mastef](https://github.com/mastef) ?

Funny enough was just looking into this and found my own comment here as well. Gotta try it out
